### ISSUE TITLE
Remove duplicate ssp-client from npm registry

### ISSUE THREAD

**Issue by mohitsuman** [sudhirverma/ssp-client#2]
Currently there are 2 npm modules in npm registry if we search for `ssp-client`.
https://www.npmjs.com/search?q=ssp-client

@sudhirverma please remove the duplicate one and update it. There should be only one ssp-client npm module with the latest changes.

- Rename the current module with **ssp-client**, NOT _ssp-clients_.
- Make the versioning.
- Add README to the npm module.

**Comment by sudhirverma** [comment]
I think now we can close this issue
